### ISSUE TITLE
can't ping instances using public IPs

### ISSUE THREAD

**Issue by ddutta** [CiscoSystems/cisco-openstack-docs#12]
Have been blocked since yesterday. Initially it was a glance issue. Now its a public IP issue. Arvind said he can ping my VMs from the cloud controller which means its a public IP issue or a lab issue.

**Comment by robertstarmer** [comment]
Investigating this now.

**Comment by robertstarmer** [comment]
Ok, the issue seems to resolve down to the need for an updated kvm/qemu package.  Soren has built, and posted to launchpad such a package.

Resolution path a) no updates to the packages: enable 'promisc' mode on your VM (this is not a good long term solution)
path b) Soren has pushed his qemu and kvm patches to launchpad

**Comment by robertstarmer** [comment]
Promisc is not necessary when using the updated KVM and Qemu packages. Now being pulled from ppa.launchpad.net/cisco-openstack-mirror.

The production and test clusters have been updated with this model.
